-- Run this in Supabase SQL Editor for the Todo app.

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists todos_user_id_created_at_idx
  on public.todos(user_id, created_at desc);

alter table public.todos enable row level security;

-- Only the owner can CRUD their todos
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='todos' and policyname='todos owner select') then
    create policy "todos owner select"
    on public.todos
    for select
    to authenticated
    using (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='todos' and policyname='todos owner insert') then
    create policy "todos owner insert"
    on public.todos
    for insert
    to authenticated
    with check (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='todos' and policyname='todos owner update') then
    create policy "todos owner update"
    on public.todos
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='todos' and policyname='todos owner delete') then
    create policy "todos owner delete"
    on public.todos
    for delete
    to authenticated
    using (auth.uid() = user_id);
  end if;
end $$;

